version: '3.8'
services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - '27077:27017'
  backend:
    build: 
      context: '../../ecommerce-backend-ts'
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DEV_DB_HOST=localhost
      - DEV_DB_PORT=27077
    ports: 
      - 3066:3066